name: deploy tf plan contains encrypted file

on: [push]

jobs:
    decrypt-certif-file:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v3
        - name: decrypt secrets.yml 
          run: gpg --quiet --bash --yes --decrypt --passphrase= "${{ secrets.GPGKEY}}"  --output data/secret.yml.gpg  data/secret.yml
        - name: result
          run: cat data/secret.yml
          


    