name: deploy tf plan contains encrypted file

on: [push]

jobs:
    decrypt-certif-file:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v3
        - name: decrypt secrets.yml 
          env: 
            passphrase: ${{ secrets.GPGKEY }}
          run: |
            ls -l 
            echo $HOME
            ls data/
            gpg --quiet --batch --yes --decrypt --passphrase="$passphrase"  --output data/secrets.yml data/secrets.yml.gpg
        - name: result
          run: cat data/secrets.yml



    