name: deploy tf plan contains encrypted file

on: 
  workflow_dispatch 

jobs:
    decrypt-certif-file:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v3
        - name: echo some env vars
          run: |
           echo $GITHUB_ACTOR
           echo $GITHUB_TOKEN


    
